### ISSUE TITLE
with the pointers would it be useful to see the intended trajectory

### ISSUE THREAD

**Issue by tarriel** [fohristiwhirl/chlorine#6]
currently if a ship dies there is no pointer, if you display the angle,thrust instead then it makes debugging collisions easier.  Like the issue you solved for me on the halite forum where I had the end points clear, but the paths actually crossed, this is only obvious if you can see the intended path.

Also it would be nice if the intended pointer was a little darker (or at least a little different to the trail) that way if you aren't watching a ship it is still clear which way it is moving.

**Comment by rooklift** [comment]
Because of the details of the game, it's a bit hard to display things really correctly. In particular, a lot of things can be said to happen *between frames*.

The deaths you see on screen (the little X marks) are what just happened. At that point, there is no ship any more to display a pointer for, and it issues no orders. If you go back one frame, the pointers in the last frame show what the ships are going to do.

(Having said that, those pointers will be short, since they're based on what actually happens. I could probably base those on intended orders instead. Would that be better?)

**Comment by rooklift** [comment]
I've made this change - pointers from colliding ships can now cross in the previous turn.

**Comment by tarriel** [comment]
I will have a look when I get home,  I was fine with the Xmarks, I just wanted to see where I told the ship to go, which is what the pointer is doing except where the ship dies, (which is the time I am most likely to want to see what I tried to do).  I love your viewer by the way,  much clearer than the halite website one.

**Comment by tarriel** [comment]
Looks good, thanks.  I can even see one of my opponents trying to move a docked ship,  which I hadn't noticed before!
